# Based on
# https://dev.to/erikhofer/build-and-publish-a-multi-platform-electron-app-on-github-3lnd

name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    env:
      GH_TOKEN: ${{ secrets.github_token }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run dist-ci
