name: Test

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    env:
      GH_TOKEN: ${{ secrets.github_token }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: latest
      - name: Install dependencies
        run: npm install
      - name: Test
        run: npm test
