name: Test

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.github_token }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: latest
      - name: Setup GUI
        run: apt update && apt upgrade -y && apt install -y xvfb
      - name: Install dependencies
        run: npm install
      - name: Test
        run: npm test
